name: build

on: 
  push:
    branches: 
      - develop

jobs:
  build-vcpkg-vs16-win32-debug:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: develop
    - name: cache
      id: cache-id
      uses: actions/cache@v1
      with:
        path: vcpkg
        key: build-vcpkg-vs16-win32-debug
    - name: install dependencies
      if: steps.cache-id.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/microsoft/vcpkg
        cd vcpkg        
        ./bootstrap-vcpkg.sh
        export PATH=$(pwd):$PATH
        vcpkg integrate install
        vcpkg install boost-asio boost-spirit boost-program-options boost-test cppcodec
        rm -rf buildtrees downloads packages    
        cd ..    
      shell: bash
    - name: build and test
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 16 2019" -A Win32 "-DCMAKE_TOOLCHAIN_FILE=..\vcpkg\scripts\buildsystems\vcpkg.cmake"
        cmake --build . --config Debug
        cmake --build . --config Debug --target run_tests
  build-vcpkg-vs16-win32-release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: develop     
    - name: cache
      id: cache-id
      uses: actions/cache@v1
      with:
        path: vcpkg
        key: build-vcpkg-vs16-win32-release
    - name: install dependencies
      if: steps.cache-id.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/microsoft/vcpkg
        cd vcpkg        
        ./bootstrap-vcpkg.sh
        export PATH=$(pwd):$PATH
        vcpkg integrate install
        vcpkg install boost-asio boost-spirit boost-program-options boost-test cppcodec
        rm -rf buildtrees downloads packages    
        cd ..    
      shell: bash
    - name: build and test
      run: |
        mkdir build
        cd build
        cmake .. -G "Visual Studio 16 2019" -A Win32 "-DCMAKE_TOOLCHAIN_FILE=..\vcpkg\scripts\buildsystems\vcpkg.cmake"
        cmake --build . --config Release
        cmake --build . --config Release --target run_tests 
  build-vcpkg-gcc-7-4-ubuntu-latest-release:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        ref: develop     
    - name: cache
      id: cache-id
      uses: actions/cache@v1
      with:
        path: vcpkg
        key: build-vcpkg-gcc-7-4-ubuntu-latest-release
    - name: install dependencies
      if: steps.cache-id.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/microsoft/vcpkg
        cd vcpkg        
        ./bootstrap-vcpkg.sh
        export PATH=$(pwd):$PATH
        vcpkg integrate install
        vcpkg install boost-asio boost-spirit boost-program-options boost-test cppcodec
        rm -rf buildtrees downloads packages    
        cd ..    
      shell: bash
    - name: build and test
      run: |
        mkdir build
        cd build
        cmake .. -G "Unix Makefiles" -Wno-dev "-DCMAKE_TOOLCHAIN_FILE=../vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_BUILD_TYPE=Release"       
        cmake --build . --config Release
        cmake --build . --config Release --target run_tests 
